// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `MapByteSeq3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


// Freeze types in this file:
// name="MapByteSeq3", key="double", value="Demo::ComplexKeySeq"

#ifndef __MapByteSeq3_h__
#define __MapByteSeq3_h__

#include <Freeze/Map.h>
#include </home/serge/Desktop/Test_Ice/code/demo.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

class MapByteSeq3KeyCodec
{
public:

    static void write(::Ice::Double, Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Ice::Double&, const Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

class MapByteSeq3ValueCodec
{
public:

    static void write(const ::Demo::ComplexKeySeq&, Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Demo::ComplexKeySeq&, const Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

typedef Freeze::Map< ::Ice::Double, ::Demo::ComplexKeySeq, MapByteSeq3KeyCodec, MapByteSeq3ValueCodec, Freeze::IceEncodingCompare > MapByteSeq3;

#endif
