// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `MapStringDouble.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


// Freeze types in this file:
// name="MapStringDouble", key="Demo::ComplexKey", value="Demo::StringDouble"

#ifndef __MapStringDouble_h__
#define __MapStringDouble_h__

#include <Freeze/Map.h>
#include </home/serge/Desktop/Test_Ice/code/demo.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

class MapStringDoubleKeyCodec
{
public:

    static void write(const ::Demo::complexKeyPtr&, Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Demo::complexKeyPtr&, const Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

class MapStringDoubleValueCodec
{
public:

    static void write(const ::Demo::StringDouble&, Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::Demo::StringDouble&, const Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

typedef Freeze::Map< ::Demo::complexKeyPtr, ::Demo::StringDouble, MapStringDoubleKeyCodec, MapStringDoubleValueCodec, Freeze::IceEncodingCompare > MapStringDouble;

#endif
